### PR TITLE
Massive URL Module Overhaul

### PR DESCRIPTION
**Pull request by KenticoDevTrev**
Hey Silvertech, Trevor Fayas (Kentico MVP)

I liked your module, we definitely need a good Url Rewrite module going, and what you did with the culture domain stuff....sooooo i kind of upgraded the module, and by upgrade i pretty much totally expanded it (spent about 15 hours)

Here's what all was done:

1. Enabled Staging, CI, Export on it
1. Added Enabled checkbox
1. Added in ability to handle Relative, Virtual Paths, or full paths
1. Added "Exact Match" to specify if the incoming request must match the url (including query strings)
1. Added Query String Appending and Hash logic, so it can properly compare, merge, and handle query strings.
1. Separated out the package into 2 separate ones, one for Admin, one for MVC, since the couple adjustments needed for the Admin (mainly the extenders and Grid.xml) leveraged libraries that are not part of the shared Kentico.Libraries nuget package, so you would be pulling non MVC code into MVC sites if installed.
1. Added a build command script and nuspect for MVC, and a nuspec overwrite for admin
1. Downgraded it to 12.0.29, as no reason to require higher than that for the module.
1. Removed the domain culture requirements, with proper fall backs so it will leverage the Culture Domain Alias if available, if not will fall back to the Site/current request domain.
1. Added {culture} handling, including auto detection based on settings, ability to overwrite culture, etc.
1. Increased performance with caching on everything, logic done in code vs. database.
1. Moved some 'magic values' such as the excluded prepend paths (ex 'api') into the settings.
1. Added query string language capabilities as well.

With this, it *should* handle every single situation out there :) 

I totally understand if this pull request will take a while to parse through, i commented as best i could, but it's a massive system to cover all the variations.  I did about 20 different test case varieties.

Contact me on the kentico community slack if you have questions!

### CODE REVIEW

**Comment by KenticoDevTrev** [comment]
Any luck on taking a look into the PR? i'm open to answering questions, or should i look to split this and just publish under a different tool, would hate to create duplicate tools vs. just having one great one.

**Comment by silvertech** [comment]
Hi KenticoDevTrev,

So incredibly sorry about not getting back to you on this! For some reason we didn't get any notifications about your PR. Just wanted to let you know that we are reviewing the changes and will respond to you as soon as we can.

Thank you!

**Comment by KenticoDevTrev** [comment]
Thanks! If you have questions just ask!

**Comment by silvertech** [comment]
Hi Trevor,

I'm having some trouble getting the updated code imported into a Kentico app for testing and verification, do you mind giving some insight on how you got it into a solution? Mostly having issues with the project's references when I try adding them to a solution. Let me know if you need more info from me. 

Alternatively, if you want to just send me the updated nuget package then I can install it on a test site and test it that way instead.

Thanks!

**Comment by KenticoDevTrev** [comment]
https://www.nuget.org/packages/HBS.KenticoURLRedirection.Admin/
https://www.nuget.org/packages/HBS.KenticoURLRedirection.MVC/

**Comment by silvertech** [comment]
Hi Trevor!

I was finally able to review your PR and get the changes working in a separate Kentico instance (sorry for the delay just been crazy busy on other work). I do have some minor changes to it if that's OK with you such as combining the main and Admin project into a single nuget package, fixing some reference issues I ran into, and updating file names to match the standard Kentico module development process (ex: AssemblyInfo -> URLRedirecitonAssemblyInfo). Let me know if you have any questions or concerns about these changes. If not, I'll approve the PR and make those minor changes. 

Thank you again so much for your contribution! We'll keep your company's name in the Module Author field and give you a shoutout in the readme file.

-SilverTech

**Comment by KenticoDevTrev** [comment]
That should be fine, although i found that you did need to have separate modules for the MVC and Admin, unless you found a way to only use the Kentico.Library nuget package in the packages and not include any dll's from the LIB folder, along with it's easier having a separate package for the Admin (using Kentico's Module export to gather everything up) and a smaller package for just the MVC.

Maybe we should go over that part, i could be wrong in needing separate ones, but i want to make sure we don't introduce bugs by mixing the admin and MVC libraries.  Do you have some time this week for a webex/teams call?

**Comment by silvertech** [comment]
Hey Trevor,

Basically all I did was add the Admin project as an external library on the main module project inside Kentico so that when it creates the NuGet package in the CMS it also includes that project's DLL with it. 
image

It's ok that it is pointing to the DLL in the bin here since this is just for the project where the module is created, this is something I've used quite a lot in the past on some other custom modules I've created that need multiple projects to be included.

I tried installing it on an MVC site via the one Nuget Package and I just told it to install the NuGet package to both the CMS project and the MVC project and it worked fine with no extra configuration needed. For non-MVC sites, the user just needs to install the NuGet pacakge to the main CMS project and it works fine. I verified this on another non-MVC site.

**Comment by KenticoDevTrev** [comment]
Hmmm, when you install the nuget into your mvc however, does it include
that admin dll?

One other downside to this approach is it copies the admin files into your
mvc project.

**Comment by silvertech** [comment]
Hi Trevor,

It does include both DLLs into the MVC project and I do see your concern that it includes unnecessary files into the MVC project. However, the main reason I wanted to change it to one package like this was so anyone would be able to take the source code, throw it into a project, import the zip package, and do any kind of customizations they want, creating their own NuGet package directly through Kentico without any external tools or scripts. That's probably a rare use case and most people will probably just install the standard module NuGet as-is from the and not even bother with the source code, but I still want this to be as easy to do as possible. Having to have the user know that only the main project can be exported through Kentico and then extra steps have to be taken to export the Admin project might end up being confusing..

Alternatively, we can also edit the instructions to tell the user to only install the NuGet pacakge to the CMS admin project in an MVC site then in the MVC project tell the user to add a reference to only the URLRedirection.dll from the package. This prevents the extra NuGet package and makes it so that no extra files are included into the MVC project. That might end up being the best compromise. I tried this on an MVC site I have and it worked without adding extra files. Let me know what your thoughts are on that.

Thanks,
SilverTech

**Comment by KenticoDevTrev** [comment]
I would keep them separate as 2 nuget packages, and then still just Export the Module thorugh Site -> Export, if someone imports this (as long as when you export it you tell it to not be sealed), they should be able to edit it afterwards.

Honestly creating 2 NuGet packages is not hard to maintain nor hard for people to install, i just postfix one with "Admin" and the other "MVC", many people have downloaded my various packages and they are often 2 separate packages, one for the MVC and one for the Admin.  

When you need to export the Admin, you use the Kentico Module Create Package, for the MVC you just use the Nuget command (I think i included it in my pull request).

This is the safest way to do it!

**Comment by silvertech** [comment]
Hi Trevor,
 
Apologies for the delayed response, had a lot of work come in internally that kept us from continuing to review this. Thank you for the feedback but we have decided to move forward with the one NuGet package solution. We will work on integrating your updates into our code base and we will give you and your company special thanks in the readme and add you to the module authors field.
 
-SilverTech

**Comment by KenticoDevTrev** [comment]
Sounds good!!

**Pull request merged**
